### Get all categories
GET http://localhost:3000/api/categories
Accept: application/json

### Create New Category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json


{
  "name" : "Books"
}

### Get Category by id
GET http://localhost:3000/api/categories/3
Accept: application/json


### Update Category by id
PUT http://localhost:3000/api/categories/2
Accept: application/json
Content-Type: application/json

{
  "name" : "Update Computer"
}

### Delete Category by id
DELETE http://localhost:3000/api/categories/1
Accept: application/json
